# Generated by Django 4.1.2 on 2022-10-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multicurrency', '0001_initial'),
        ('emails', '0001_initial'),
        ('session_management', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('once_only', 'once_only'), ('user_chosen', 'user_chosen')], default='once_only', max_length=300)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_without_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('num_sold', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Single Choice', 'Single Choice'), ('Multiple Choice', 'Multiple Choice'), ('Text Input', 'Text Input'), ('Char Input', 'Char Input'), ('Image Input', 'Image Input'), ('Email Input', 'Email Input'), ('password', 'password'), ('Sales Page', 'Sales Page')], max_length=300)),
                ('title', models.CharField(max_length=400)),
                ('number', models.IntegerField()),
                ('description', tinymce.models.HTMLField(blank=True, max_length=10000, null=True)),
                ('skippable', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/images')),
                ('input_placeholder', models.CharField(blank=True, max_length=300, null=True)),
                ('image_upload_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('setUserPreferences', 'setUserPreferences'), ('feedback', 'feedback'), ('updateUserPreferences', 'updateUserPreferences')], default='setUserPreferences', max_length=300)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('display_name', models.CharField(max_length=300)),
                ('unique_id', models.CharField(blank=True, max_length=400, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_management.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.product')),
            ],
        ),
        migrations.CreateModel(
            name='UserImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_uploads/')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('response_id', models.CharField(max_length=500, unique=True)),
                ('steps_completed', models.CharField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.quiz')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_management.usersession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid')], default='created', max_length=300)),
                ('user_chosen_price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('user_chosen_interval_months', models.IntegerField(blank=True, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=500, null=True)),
                ('order_number', models.CharField(blank=True, max_length=500, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='multicurrency.currency')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.useremail')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.product')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.response')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session_management.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('option_image_icon', models.ImageField(blank=True, null=True, upload_to='question_choice_images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_preference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userpreferencetype'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz_backend.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_choice',
            field=models.ManyToManyField(blank=True, to='quiz_backend.questionchoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_backend.response'),
        ),
    ]
