# Generated by Django 4.1.2 on 2022-10-04 12:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ending',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True),
        ),
    ]
