# Generated by Django 4.1.5 on 2023-01-02 15:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0002_quizpageelement_titlepageelement_quizpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='quizpageelement',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizCreation.quizpage'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TitlePageElement',
        ),
        migrations.AddField(
            model_name='textelement',
            name='page_element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.quizpageelement'),
        ),
    ]
