# Generated by Django 4.1.5 on 2023-01-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0008_multiplechoiceelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=300)),
                ('multiple_choice_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.multiplechoiceelement')),
            ],
        ),
    ]
