# Generated by Django 4.1.5 on 2023-04-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0009_multiplechoicechoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizpage',
            old_name='name',
            new_name='title',
        ),
    ]
