# Generated by Django 4.1.8 on 2023-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0013_singlechoiceelement_singlechoicechoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicechoice',
            name='is_correct_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singlechoicechoice',
            name='is_correct_choice',
            field=models.BooleanField(default=False),
        ),
    ]
