# Generated by Django 4.1.8 on 2023-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0014_multiplechoicechoice_is_correct_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicechoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choice_images/'),
        ),
        migrations.AddField(
            model_name='singlechoicechoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choice_images/'),
        ),
    ]
