# Generated by Django 4.1.8 on 2023-04-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0016_agreedisagree'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreeDisagreeRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=10000)),
                ('agree_disagree_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.agreedisagree')),
            ],
        ),
    ]
