# Generated by Django 4.1.8 on 2023-04-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0017_agreedisagreerow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreedisagreerow',
            name='title',
            field=models.TextField(max_length=10000),
        ),
    ]
