# Generated by Django 4.1.8 on 2023-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0019_alter_textelement_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
