# Generated by Django 4.1.8 on 2023-04-15 10:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0020_userquiz_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='quiz_confirmation_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
