# Generated by Django 4.1.8 on 2023-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0021_userquiz_quiz_confirmation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreedisagree',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
