# Generated by Django 4.1.8 on 2023-04-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0023_imagedisplayelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
