# Generated by Django 4.1.8 on 2023-04-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0024_userquiz_stripe_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfiedUnsatisfied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('page_element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.quizpageelement')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfiedUnsatisfiedRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('title', models.TextField(max_length=10000)),
                ('satisfied_unsatisfied_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.satisfiedunsatisfied')),
            ],
        ),
    ]
