# Generated by Django 4.1.8 on 2023-05-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0025_satisfiedunsatisfied_satisfiedunsatisfiedrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpageelement',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
