# Generated by Django 4.1.8 on 2023-05-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0026_quizpageelement_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpageelement',
            name='required',
        ),
        migrations.AddField(
            model_name='charinputelement',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailinputelement',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplechoiceelement',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='numberinputelement',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textinputelement',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
