# Generated by Django 4.1.8 on 2023-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0027_remove_quizpageelement_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlechoiceelement',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
