# Generated by Django 4.1.8 on 2023-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0028_singlechoiceelement_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreedisagreerow',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='satisfiedunsatisfiedrow',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
