# Generated by Django 4.1.8 on 2023-05-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0030_reviewstars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpage',
            name='title',
        ),
    ]
