# Generated by Django 4.1.8 on 2023-05-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0033_dropdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownChocie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=300)),
                ('is_correct_choice', models.BooleanField(default=False)),
                ('dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.dropdown')),
            ],
        ),
    ]
