# Generated by Django 4.1.8 on 2023-05-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0034_dropdownchocie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DropdownChocie',
            new_name='DropdownChoice',
        ),
    ]
