# Generated by Django 4.1.8 on 2023-05-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0036_onetotenelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Upload your own', 'Upload your own'), ('Youtube', 'Youtube'), ('Vimeo', 'Vimeo')], max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='user_quiz_videos/')),
                ('page_element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.quizpageelement')),
            ],
        ),
    ]
