# Generated by Django 4.1.8 on 2023-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0037_videoelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoelement',
            name='type',
            field=models.CharField(blank=True, choices=[('Upload', 'Upload'), ('Youtube', 'Youtube'), ('Vimeo', 'Vimeo')], max_length=1000, null=True),
        ),
    ]
