# Generated by Django 4.1.8 on 2023-05-14 23:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0038_alter_videoelement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='type',
            field=models.CharField(blank=True, choices=[('Upload', 'Upload'), ('Youtube', 'Youtube')], max_length=1000, null=True),
        ),
    ]
