# Generated by Django 4.1.2 on 2022-10-04 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multicurrency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('enable_pixels', models.BooleanField(default=True)),
                ('analytics_base', models.TextField(blank=True, max_length=5000)),
                ('analytics_content_view', models.TextField(blank=True, max_length=5000)),
                ('analytics_lead', models.TextField(blank=True, max_length=5000)),
                ('analytics_purchase', models.TextField(blank=True, max_length=5000)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=250, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latest_fb_clid', models.CharField(blank=True, max_length=500, null=True)),
                ('latest_fbp', models.CharField(blank=True, max_length=500, null=True)),
                ('latest_t_clid', models.CharField(blank=True, max_length=500, null=True)),
                ('ip', models.CharField(blank=True, max_length=2000, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=2000, null=True)),
                ('country_code', models.CharField(blank=True, max_length=250, null=True)),
                ('add_user_agent_to_exclusion_list', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multicurrency.currency')),
                ('email_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.useremail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=250, null=True)),
                ('audience', models.CharField(blank=True, max_length=250, null=True)),
                ('ad', models.CharField(blank=True, max_length=250, null=True)),
                ('user_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session_management.usersession')),
            ],
        ),
    ]
