# Generated by Django 4.1.8 on 2023-05-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizPayments', '0001_initial'),
        ('quizRender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizRender.response'),
        ),
    ]
