# Generated by Django 4.1.8 on 2023-04-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizPayments', '0004_rename_payment_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
