# Generated by Django 4.1.8 on 2023-04-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizRender', '0003_answer_question_agree_disagree_alter_answer_question'),
        ('quizPayments', '0005_order_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizRender.response'),
        ),
    ]
