# Generated by Django 4.1.8 on 2023-05-08 16:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(required=False)), ('content', wagtail.blocks.RichTextBlock(required=False))]))], use_json_field=False),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, null=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='second_intro',
            field=wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, null=True, use_json_field=False),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='text_before_content',
            field=wagtail.fields.StreamField([('article_section', wagtail.blocks.StructBlock([('content', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, null=True, use_json_field=False),
        ),
    ]
