# Generated by Django 4.1.8 on 2023-04-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentstatus',
            name='status',
            field=models.CharField(choices=[('free_trial', 'free_trial'), ('active', 'active'), ('free', 'free')], max_length=300),
        ),
    ]
