# Generated by Django 4.1.5 on 2023-04-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizCreation', '0010_rename_name_quizpage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('response_id', models.CharField(max_length=500, unique=True)),
                ('steps_completed', models.CharField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.userquiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=5000)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.quizpageelement')),
                ('question_choice', models.ManyToManyField(blank=True, null=True, to='quizCreation.multiplechoicechoice')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizRender.response')),
            ],
        ),
    ]
