# Generated by Django 4.1.8 on 2023-05-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session_management', '0001_initial'),
        ('quizCreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('response_id', models.CharField(max_length=500, unique=True)),
                ('steps_completed', models.CharField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.userquiz')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizRenderSession', to='session_management.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=5000)),
                ('dropdown_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.dropdownchoice')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.quizpageelement')),
                ('question_agree_disagree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.agreedisagreerow')),
                ('question_choice', models.ManyToManyField(blank=True, null=True, to='quizCreation.multiplechoicechoice')),
                ('question_satisfied_unsatisfied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.satisfiedunsatisfiedrow')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizRender.response')),
                ('single_question_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.singlechoicechoice')),
            ],
        ),
    ]
