# Generated by Django 4.1.5 on 2023-04-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session_management', '0001_initial'),
        ('quizRender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizRenderSession', to='session_management.usersession'),
        ),
    ]
