# Generated by Django 4.1.8 on 2023-04-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0018_alter_agreedisagreerow_title'),
        ('quizRender', '0002_response_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_agree_disagree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.agreedisagreerow'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.quizpageelement'),
        ),
    ]
