# Generated by Django 4.1.8 on 2023-04-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0024_userquiz_stripe_public_key_and_more'),
        ('quizRender', '0003_answer_question_agree_disagree_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='single_question_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.singlechoicechoice'),
        ),
    ]
