# Generated by Django 4.1.8 on 2023-04-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0025_satisfiedunsatisfied_satisfiedunsatisfiedrow'),
        ('quizRender', '0004_answer_single_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_satisfied_unsatisfied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.satisfiedunsatisfiedrow'),
        ),
    ]
