# Generated by Django 4.1.8 on 2023-05-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizCreation', '0035_rename_dropdownchocie_dropdownchoice'),
        ('quizRender', '0005_answer_question_satisfied_unsatisfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dropdown_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizCreation.dropdownchoice'),
        ),
    ]
