# Generated by Django 4.1.8 on 2023-05-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizCreation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_id', models.CharField(max_length=7000)),
                ('integration_type', models.CharField(choices=[('facebook', 'facebook'), ('tiktok', 'tiktok')], max_length=1000)),
                ('conv_api_token', models.CharField(max_length=7000)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.userquiz')),
            ],
        ),
    ]
