# Generated by Django 4.1.8 on 2023-04-16 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizCreation', '0022_alter_agreedisagree_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_id', models.CharField(max_length=7000)),
                ('pixel_type', models.CharField(blank=True, choices=[('facebook', 'facebook'), ('tiktok', 'tiktok')], max_length=1000, null=True)),
                ('conv_api_token', models.CharField(blank=True, max_length=7000, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizCreation.userquiz')),
            ],
        ),
    ]
