# Generated by Django 4.1.8 on 2023-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizConversionTracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='conv_api_token',
            field=models.CharField(default='1', max_length=7000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pixel',
            name='pixel_type',
            field=models.CharField(choices=[('facebook', 'facebook'), ('tiktok', 'tiktok')], default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
