# Generated by Django 4.1.2 on 2022-10-04 09:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('free_tier', 'free_tier'), ('starter', 'starter'), ('professional', 'professional'), ('business', 'business'), ('enterprise', 'enterprise')], max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('tier_ranking', models.IntegerField(unique=True)),
                ('badge_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
            ],
        ),
    ]
