# Generated by Django 4.1.2 on 2022-10-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_secondary_button_css',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_secondary_button_focus_css',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_secondary_button_hover_css',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
